modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPLv3"
[[mods]] #mandatory
modId="incineratorstryhard" #mandatory
version="1.20.1-1.0.5" #mandatory
displayName="Cataclysm: Incinerator's Try Hard" #mandatory
authors="Rinko1231" #optional
description="Custom the damage, ignic circle and charging time of the Incinerator, The Immolator, Tidal Claws and some other Catalysm gears!"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.incineratorstryhard]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.incineratorstryhard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
